FROM runpod/comfyui:1.2.5

COPY --chmod=755 ./start.sh /start.sh
COPY ./comfyui_args.txt /opt/import/comfyui_args.txt
COPY ./workflows /opt/import/workflows
# COPY ./models /opt/import/models
# COPY ./custom_nodes /opt/import/custom_nodes/
