FROM runpod/comfyui:1.2.1

COPY ./start.sh /start.sh
RUN chmod +x /start.sh     
COPY ./workflows /opt/import/workflows
# COPY ./models /opt/import/models
# COPY ./custom_nodes /opt/import/custom_nodes/